'use strict';

// The carrier model's barrel (docs/adr/0064). Every public name is written out
// so Node's CJS named-export detection sees it from an .mjs import — a spread
// of require() would hide them (L4 briefing trap T12).

const {
  normDeg,
  reciprocal,
  angularDiff,
  gridToTrue,
  toMagnetic,
} = require('./angles');
const {
  CASES,
  LEGAL_CASE_TRANSITIONS,
  DEFAULT_CASE,
  isCase,
  initialRecoveryCase,
  normalizeRecoveryCase,
  setCase,
  caseFloor,
  caseAdvisory,
  isSequencedCase,
} = require('./recovery-case');
const {
  ENTRY_KEYS,
  STACK_KEYS,
  ENTRY_STATUSES,
  STACK_DEFAULTS,
  DEFAULT_STACK_ID,
  STACK_OP_KINDS,
  RADIAL_TOLERANCE_DEG,
  CASE_I_MIN_ANGELS,
  CASE_I_MAX_ANGELS,
  emptyStack,
  validateStack,
  normalizeStack,
  deriveEntry,
  deriveStack,
  checkConsistency,
  insertAt,
  append,
  move,
  remove,
  closeUp,
  markPushed,
  setCharlieTime,
  setCaseIAngels,
  setMarshalRadial,
  applyStackOp,
} = require('./marshal-stack');
const {
  SHIP_CATEGORY,
  ANGLED_DECK_BY_TYPE,
  DEFAULT_HULL,
  SHIP_INPUT_KEYS,
  ALTIMETER_MIN_INHG,
  ALTIMETER_MAX_INHG,
  validateHullConfig,
  matchHullTrack,
  hullMatchProblem,
  computeFinalBearing,
  inHgFromPa,
  buildShipState,
  staleFrom,
  shipStateChanged,
  defaultShipInputs,
  applyShipStateInput,
  normalizeShipInputs,
  displayBearing,
} = require('./ship-state');
const {
  APPROACH_TYPES,
  APPROACH_BUTTON_MIN,
  APPROACH_BUTTON_MAX,
  CARRIER_FLIGHT_FIELDS,
  MARSHAL_MESSAGE_FIELDS,
  defaultCarrierFlight,
  validateCarrierFlightField,
  setCarrierFlightField,
  normalizeCarrierFlight,
  carrierFlightOf,
  marshalMessage,
} = require('./flight-record');
const {
  TRIGGER_TYPES,
  APP_LANES,
  CARRIER_TRANSFERS,
  GUIDE_TRANSFER_KINDS,
  validateCarrierTransfer,
  laneFor,
  assignLanes,
} = require('./transfers');

module.exports = {
  normDeg,
  reciprocal,
  angularDiff,
  gridToTrue,
  toMagnetic,
  CASES,
  LEGAL_CASE_TRANSITIONS,
  DEFAULT_CASE,
  isCase,
  initialRecoveryCase,
  normalizeRecoveryCase,
  setCase,
  caseFloor,
  caseAdvisory,
  isSequencedCase,
  ENTRY_KEYS,
  STACK_KEYS,
  ENTRY_STATUSES,
  STACK_DEFAULTS,
  DEFAULT_STACK_ID,
  STACK_OP_KINDS,
  RADIAL_TOLERANCE_DEG,
  CASE_I_MIN_ANGELS,
  CASE_I_MAX_ANGELS,
  emptyStack,
  validateStack,
  normalizeStack,
  deriveEntry,
  deriveStack,
  checkConsistency,
  insertAt,
  append,
  move,
  remove,
  closeUp,
  markPushed,
  setCharlieTime,
  setCaseIAngels,
  setMarshalRadial,
  applyStackOp,
  SHIP_CATEGORY,
  ANGLED_DECK_BY_TYPE,
  DEFAULT_HULL,
  SHIP_INPUT_KEYS,
  ALTIMETER_MIN_INHG,
  ALTIMETER_MAX_INHG,
  validateHullConfig,
  matchHullTrack,
  hullMatchProblem,
  computeFinalBearing,
  inHgFromPa,
  buildShipState,
  staleFrom,
  shipStateChanged,
  defaultShipInputs,
  applyShipStateInput,
  normalizeShipInputs,
  displayBearing,
  APPROACH_TYPES,
  APPROACH_BUTTON_MIN,
  APPROACH_BUTTON_MAX,
  CARRIER_FLIGHT_FIELDS,
  MARSHAL_MESSAGE_FIELDS,
  defaultCarrierFlight,
  validateCarrierFlightField,
  setCarrierFlightField,
  normalizeCarrierFlight,
  carrierFlightOf,
  marshalMessage,
  TRIGGER_TYPES,
  APP_LANES,
  CARRIER_TRANSFERS,
  GUIDE_TRANSFER_KINDS,
  validateCarrierTransfer,
  laneFor,
  assignLanes,
};
